urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (C) 2012 Étienne Loks  <etienne.loks_AT_peacefrogsDOTnet>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# See the file COPYING for details.

from django.conf import settings
from django.conf.urls.defaults import *

from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()
urlpatterns = patterns('django.views.static',
    (r'^%s(?P<path>.*)' % settings.MEDIA_URL[1:], 'serve',
     {'document_root': settings.MEDIA_ROOT}),
)
urlpatterns += staticfiles_urlpatterns()

urlpatterns += patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    url(r'^(?P<area_name>[a-zA-Z0-9_-]+/)?edit/$', 'chimere_saclay.views.edit',
        name="edit"),
    url(r'^(?P<area_name>[a-zA-Z0-9_-]+/)?edit/(?P<item_id>\w+)/(?P<submited>\w+)?$',
            'chimere_saclay.views.edit', name="edit-item"),
    url(r'^(?P<area_name>[a-zA-Z0-9_-]+/)?edit-event/$',
        'chimere_saclay.views.edit', name="edit-event", kwargs={'event':True}),
    url(r'^(?P<area_name>[a-zA-Z0-9_-]+/)?edit-event/(?P<item_id>\w+)/(?P<submited>\w+)?$',
        'chimere_saclay.views.edit', kwargs={'event':True},
        name="edit-event-item"),
    url(r'^(?P<area_name>[a-zA-Z0-9_-]+/)?edit-route/$',
        'chimere_saclay.views.edit_route', name="edit-route"),
    url(r'^(?P<area_name>[a-zA-Z0-9_-]+/)?edit-route/(?P<item_id>\w+)/(?P<submited>\w+)?$',
        'chimere_saclay.views.edit_route', name="edit-route-item"),
    url(r'^(saclay/)?$', 'chimere_saclay.views.index_saclay',
        name="index-saclay"),
    url(r'^', include('chimere.urls', namespace="chimere")),
)

forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (C) 2012  Étienne Loks  <etienne.loks_AT_peacefrogsDOTnet>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# See the file COPYING for details.

"""
Forms
"""
from django import forms
from django.utils.translation import ugettext as _

from chimere.models import SubCategory
from chimere.forms import MarkerForm as BaseMarkerForm, \
                          RouteForm as BaseRouteForm
from chimere.widgets import TextareaWidget

class MarkerForm(BaseMarkerForm):
    categories = forms.ChoiceField(choices=[], widget=forms.Select)
    description = forms.CharField(widget=TextareaWidget, required=False)

    def __init__(self, *args, **kwargs):
        super(MarkerForm, self).__init__(*args, **kwargs)
        self.fields['categories'].widget.choices = [('', _(u"Select"))] + \
                           SubCategory.getAvailableTuples(item_types=['M', 'B'])

    def clean_categories(self):
        cats = self.cleaned_data.get('categories')
        if cats:
            if type(cats) not in (list, tuple):
                self.cleaned_data['categories'] = [cats]
        return self.cleaned_data['categories']

class RouteForm(BaseRouteForm):
    categories = forms.ChoiceField(choices=[], widget=forms.Select)
    description = forms.CharField(widget=TextareaWidget, required=False)

    def __init__(self, *args, **kwargs):
        super(RouteForm, self).__init__(*args, **kwargs)
        self.fields['categories'].widget.choices = [('', _(u"Select"))] + \
                           SubCategory.getAvailableTuples(item_types=['R', 'B'])

    def clean_categories(self):
        cats = self.cleaned_data.get('categories')
        if cats:
            if type(cats) not in (list, tuple):
                self.cleaned_data['categories'] = [cats]
        return self.cleaned_data['categories']

templates/chimere/base.html
{% extends "base.html" %}
{% load chimere_tags i18n %}
{% block extra_head %}
<link rel="shortcut icon" href="{{ STATIC_URL }}saclay/images/favicon.png"/>
<link rel="stylesheet" href="{{ STATIC_URL }}chimere/css/styles.css" />
<link rel="stylesheet" href="{{ STATIC_URL }}chimere/css/print.css" media='print'/>
<link rel="stylesheet" href="{{ STATIC_URL }}saclay/css/styles.css" />
{% for css in EXTRA_CSS %}<link rel="stylesheet" href="{{ css }}" />{% endfor %}
<link rel="stylesheet" href="{{ STATIC_URL }}saclay/css/print.css" media='print'/>
{% if MOBILE %}
<link rel="stylesheet" href="{{ STATIC_URL }}chimere/css/mobile.css" />
<link rel="stylesheet" href="{{ STATIC_URL }}saclay/css/mobile.css" />
<script src="{{ STATIC_URL }}chimere/js/mobile.chimere.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}saclay/js/mobile.chimere.js" type="text/javascript"></script>{%endif%}
{% if css_area %}
<link rel="stylesheet" href="{{ css_area }}" />{% endif %}
{% endblock %}
{% block header %}
<noscript>
    <div id="no-js-message">
        <p id='no-js' class='warning'>{% trans "You must enable JavaScript in your browser to display Chimère."%}</p>
    </div>
</noscript>
    {% block page_title %}
        {% include "chimere/blocks/page_title.html" %}
    {% endblock %}
    {% block actions %}
        {% include "chimere/blocks/actions.html" %}
    {% endblock %}
{% endblock %}
{% block content %}
    {% block top %}{% endblock %}
    {% block message_map %}{% endblock %}
    {% block message_edit %}{% endblock %}
    {% block bottom %}{% endblock %}
{% endblock %}
{% block footer %}
    {% include "chimere/blocks/footer.html" %}
{% endblock %}

templates/chimere/default_extra_page.html
<h2 id='dialog-title'>{{title}}</h2>
<div class='content'>
{{content|safe}}
</div>

templates/chimere/detail.html
{% load i18n sanitize chimere_tags %}
<a href='#' class='close_img'>{% trans "Close"%}</a>
<h4>{{ marker.name }}</h4>
<div id='detail_content'>
    {% if marker.default_pictures or marker.default_pictures or marker.default_multimedia_items%}
    <div class='small-gallery'>
    {% for picture in marker.default_pictures %}
        {% multimedia_render picture %}
    {%endfor%}
    {% for multimedia_item in marker.default_multimedia_items %}
        {% multimedia_render multimedia_item %}
    {%endfor%}
    {% for item in marker.multimedia_items %}
        {% multimedia_render item %}
    {%endfor%}
    </div>
    {%endif%}
    <div>
        {% if dated %}
        <p id='detail_start_date'><label>{% trans "Date:" %}</label> <span>{{marker.start_date|date:"D d M Y"}}
        {% if marker.end_date %} - {{marker.end_date|date:"D d M Y"}}</p>{% endif %}</span>
        {% endif %}
        {% if marker.description %}
        <div id='description_long_{{marker.pk}}' class='description'>{{ marker.description|sanitize:"p b i br hr strong em span:style a:href:target ul li ol h1 h2 h3 h4 table td tr th"|safe}}</div>
        {% endif %}
        {% for property in marker.getProperties %}{% if property.value %}
        <div class='properties' id='{{property.propertymodel.getAttrName}}'><strong>{{property.propertymodel.name}}</strong> : {% if 'http://' in property.value or 'https://' in property.value %}<a href='{{ property.value|sanitize:""}}'>{%endif%}{{ property.value|sanitize:"p b i br hr strong em span:style a:href:target ul li ol h1 h2 h3 h4 table td tr th"|safe}}{% if 'http://' in property.value or 'https://' in property.value %}</a>{%endif%}</div>
        {%endif%}{% endfor %}
    </div>
</div>
<div id='detail_footer'>
    <div id='detail-action-bar'>
        {%if routing_enabled%}<a class='detail_from' href='#'>{% trans "From" context "routing" %}</a>
        | <a class='detail_to' href='#'>{% trans "To" context "routing" %}</a>
        | {% endif %}<a class='detail_zoomin' href='#'>{% trans "Zoom in" %}</a>
        | <a class='detail_zoomout' href='#'>{% trans "Zoom out" %}</a>
    </div>
    <ul class='share'>
        <li><a href="{{modif_by_email}}">{% trans "Propose a modification" %}</a></li>
        <li class='sep'>&ndash;</li>
    </ul>
    {% share_bar marker.name %}
    {% comment %}
    <a href='{% if marker.route %}{% url chimere:editroute-item area_name_slash|default_if_none:"" marker.route.pk "" %}{%else%}{% url chimere:edit-item area_name_slash|default_if_none:"" marker.pk "" %}{%endif%}'>
        {% trans "Submit a modification" %}
    </a>
    {% endcomment %}
</div>
<script language='javascript' type='text/javascript'>
<!--
$('html').addClass('js-on');
$(function(){
    $("#gallery-{{marker.pk}}").dialog({title:"{{marker.name}}", autoOpen: false,
                           height: "auto", width: "auto", dialogClass:'no-titlebar'});
    $('div.media-player').jmeEmbedControls();
    $('.tabs').tabs({
        select: function(event, ui) {
            //pause all medias
            $('video').each(function(index){$(this).pause()});
            $('audio').each(function(index){$(this).pause()});
            //start current tabvideo
            $('ui.panel video').each(function(index){
                //prevents a Flash-Bug in IE with newest Flash-Player
                $(this).reinitMedia({queue: true})
                .play()
            ;});
            $('ui.panel audio').each(function(index){
                //prevents a Flash-Bug in IE with newest Flash-Player
                $(this).reinitMedia({queue: true})
                .play()
            ;});
        }
    });
    $('.video div.media-player').bind('useractive', function(){
        $('div.media-controls', this).stop().animate({opacity: 1});
    }).bind('userinactive', function(){
        $('div.media-controls', this).stop().animate({opacity: 0});
    });
});
$("#gallery-{{marker.pk}}").bind( "dialogopen", function(event, ui) {
    $("#gallery-{{marker.pk}}").dialog("option", "height", 'auto');
    $("#gallery-{{marker.pk}}").dialog("option", "width", 'auto');
    $("#gallery-{{marker.pk}}").dialog("option", "position", ['center', 'center']);
});
$("#gallery-{{marker.pk}}").bind( "dialogclose", function(event, ui) {
    //pause all medias
    $('video').each(function(index){$(this).pause()});
    $('audio').each(function(index){$(this).pause()});
});
$('#show_gallery_link').click(function(){
    $("#gallery-{{marker.pk}}").dialog('open');
    return false;
});
// -->
</script>

templates/chimere/edit.html
{% load i18n chimere_tags adminmedia inline_formset%}
    {% if submited %}{% submited %}{% endif %}
    <div class='edit'>
    {% if event %}<h3>{% trans "Add an event" %}</h3>
    {% else %}
    {% if route %}<h3>{% trans "Add a route" %}</h3>
    {% else %}<h3>{% trans "Add a location" %}</h3>
    {% endif%}{% endif%}
    <div class='notice'>
    {% if event %}
    <p>Vous pouvez utiliser le formulaire ci-dessous pour partager avec nous un événement public à venir sur le territoire. Merci de ne renseigner un événement que lorsqu’il est confirmé, et de nous faire part le plus rapidement possible de toute modification le concernant.  Pensez à indiquer la date de début et de fin.
Les évènements à caractère politique, confessionnel ainsi que ceux relevant de prosélytisme divers ne seront pas affichés sur le site.</p>
    {% else %}
    {% if route %}
    <p>Vous pouvez utiliser le formulaire ci-dessous pour proposer un itinéraire de promenade sur le territoire. Merci de renseigner seulement un itinéraire que vous avez déjà pratiqué à plusieurs reprises et avec succès, afin d’éviter des déconvenues à ceux qui s’en inspireraient.</p>
    {% else %}
    <p>Vous pouvez utiliser le formulaire ci-dessous pour proposer un lieu utile ou remarquable sur le plateau. Merci de vous assurer au préalable de l’exactitude des informations fournies et de visiter les rubriques déjà existantes pour harmoniser les informations soumises.</p>
    {% endif%}{% endif%}
    </div>
    <p class='notice'>* {% trans "indicates a mandatory field" %}</p>
    <form enctype="multipart/form-data" method='post' action='{% if route%}{% url edit-route%}{%else%}{% url edit %}{% endif %}' id='proposition_form'>
    {% csrf_token %}
    {% if not route %}
    <div class="fieldWrapper point_label">
        <label class='error'>{% trans "Select a location for this new site" %}</label>
        <input type='hidden' id='id_point' name='point'/>
    </div>{% endif %}
    <div class="fieldWrapper">
        <label for="id_name">{%if route%}{% trans "Name of the route"%}{% else %}{% if event %}{% trans "Name of the event"%}{% else %}{% trans "Name of the location"%}{% endif %}{% endif %} <span class='mandatory'>*</span></label>
        {% if form.name.errors %}<div class='errors'>{{ form.name.errors }}</div>{% endif %}
        {{ form.name }}
    </div>
    <div class="fieldWrapper">
      <label for="id_subcategory">{% trans "Category" %} <span class='mandatory'>*</span></label>
        {% if form.categories.errors %}<div class='errors'>{{ form.categories.errors }}</div>{% endif %}
      {{ form.categories }}
    </div>
    <hr class='clean'/>
    {% if event %}
    <div class="fieldWrapper" id='div_start_date'>
        <label for="id_start_date">{% trans "Start date" %} <span class='mandatory'>*</span></label>
        {{ form.start_date.errors }}
        {{ form.start_date }}
    </div>
    <div class="fieldWrapper" id='div_end_date'>
        <label for="id_end_date">{% trans "End date" %}</label>
        {{ form.end_date.errors }}
        {{ form.end_date }}
    </div>
    <hr class='clean'/>
    {% endif %}
    {% for field in form %}
        {% for property in properties %}
            {% ifequal field.name property.getNamedId %}
                <div class="fieldWrapper single-line">
                    <label for="id_{{field.name}}">{% trans field.label %}{% if property.mandatory %} <span class='mandatory'>*</span>{% endif %}</label>
                    {% if field.errors %}<div class='errors'>{{ field.errors }}</div>{% endif %}
                    {{ field }}
                </div>
            {%endifequal%}
        {%endfor%}
    {%endfor%}
    <div class="fieldWrapper">
        <label for="id_description">{% trans "Description" %}</label>
        {{ form.description.errors }}
        {{ form.description }}
        <p class="help">{{ form.description.help_text }}</p>
    </div>

    {% if filtered_properties %}
    <script type='text/javascript'>
        <!--
        var cat_filters = new Array();
        var cat_to_hide = new Array();
        {% for property in filtered_properties %}
        cat_to_hide.push('#id_{{property.getNamedId}}');
        {% for subcat in property.subcategories.all %}
        if(!cat_filters['{{subcat.id}}']) cat_filters['{{subcat.id}}'] = new Array();
        cat_filters['{{subcat.id}}'].push('#id_{{property.getNamedId}}');
        {% endfor %}
        {% endfor %}
        $('#id_categories').change(function(){
            for (idx in cat_to_hide){
                $(cat_to_hide[idx]).parent().hide();
            }
            var vals = $(this).val();
            for (val_id in vals){
                var val = vals[val_id];
                for (ids in cat_filters[val]){
                    $(cat_filters[val][ids]).parent().show();
                }
            }
        });
        $('#id_categories').change();
        // -->
    </script>
    {% endif %}
    {% if route %}
    <h4 id='head_route' class='toggle maximized'>{% trans "Route" context "form" %} <span class='mandatory'>*</span></h4>
    <div id='itinerary_field_contener'>
        <input id='id_route' name='route' type='hidden'/>
        <label class='error'>{% trans "Select a route for this new site (have you submit the search?)" %}</label>
    <div id='itinerary_field'>{% if not itinerary_form %}
    <div class='notice'><p>Cliquez sur la carte pour dessiner le trajet.</p></div>
    {% endif %}</div>
    <hr class='clean'/>
    </div>
    {% endif %}
    <h4 id='head_multimedia'><span>Images, audios, vidéos</span><span id="add_multimedia_list">Ajouter</span></h4>
    {% alternate_multimedia formset_multi formset_picture %}
    <h4 id='head_personalform' class='toggle maximized'>{% trans "Personal information"%}</h4>
    <div id='personalform'>
        <div class="fieldWrapper single-line">
            <label for="id_submiter_email">{% trans "Email"%} <span class='mandatory'>*</span></label>
            {% if form.submiter_email.errors %}<div class='errors'>{{ form.submiter_email.errors }}</div>{% endif %}
            {{ form.submiter_email }}
        </div>
        <div class="fieldWrapper single-line">
            <label for="id_submiter_name">{% trans "Name"%}</label>
            {% if form.submiter_name.errors %}<div class='errors'>{{ form.submiter_name.errors }}</div>{% endif %}
            {{ form.submiter_name }}
        </div>
        <div class="fieldWrapper">
            <label for="id_submiter_comment">{% trans "Comment" %}</label>
            {% if form.submiter_comment.errors %}<div class='errors'>{{ form.submiter_comment.errors }}</div>{% endif %}
            {{ form.submiter_comment }}
        </div>
    </div>
    <div id='upload_in_progress'>
        <p>{% trans "Upload in progress. Please wait..." %}</p>
        <p><img src='{{STATIC_URL}}chimere/img/ajax-loader.gif'/></p>
    </div>
    <p><span id='proposition_form_submit'>{% trans 'Propose'%}</span></p>
    <script text='text/javascript'>
        <!--
        $(function(){
            tinyMCE.init({
                mode : "textareas",
                theme : "advanced",
                editor_selector : "mceEditor",
                relative_urls : false,
                theme_advanced_buttons1 : "bold,italic,underline,strikethrough,separator,bullist,numlist,separator,hr,separator,link",
                theme_advanced_buttons2 : "",
                theme_advanced_buttons3 : ""
            });

            {% if route and itinerary_form %}
            $("#chimere_itinerary_form").appendTo($("#itinerary_field"));
            $('#main_map').chimere('updateRoutingInput');
            {% else %}$('#main_map').chimere('updateMarkerInput');{% endif %}
            $('.toggle').click(function(){
                var div_item = $(this).next();
                div_item.toggle();
                if (div_item.is(":visible")){
                    $(this).removeClass('minified');
                    $(this).addClass('maximized');
                } else {
                    $(this).addClass('minified');
                    $(this).removeClass('maximized');
                }
            });
            $( "#upload_in_progress" ).dialog({
                 modal: true,
                 resizable:false,
                 height:110,
                 autoOpen:false,
                 dialogClass:'alert-box'
                }
            );
            $('#proposition_form_submit').click(function(){
                // JS tests because if a file is submited there is no way
                // to refill the form with (browser security issue)
                tinyMCE.triggerSave();
                validation = [{%if route%}
                    'id_route'{%else%}'id_point'{% endif %},
                    'id_name',
                    'id_categories',{% if event %}
                    'id_start_date',{% endif %}
                    'id_submiter_email'
                ];
                var validated = true;
                for (var idx=0; idx<validation.length ;idx++){
                    var input_id = validation[idx];
                    var val = jQuery('#'+input_id).val();
                    if (!val || val == '0' ||
                            (input_id == 'id_submiter_email' && 
                            !isValidEmailAddress(val))){
                        jQuery('#'+input_id).parent().addClass('warning');
                        jQuery('#'+input_id).parent().addClass('error');
                        validated = false;
                    } else {
                        jQuery('#'+input_id).parent().removeClass('warning');
                        jQuery('#'+input_id).parent().removeClass('error');
                    }
                }
                if (!validated){
                    alert("{%trans "There are missing/erroneous fields."%}");
                    $("#panel").scrollTop(0);
                    return false;
                }
                $("#proposition_form").ajaxForm();
                $("#upload_in_progress").dialog('open');
                $("#proposition_form").ajaxSubmit({
                    target:"#frm-edit-marker",
                    success:function(msg){
                        $("#panel").scrollTop(0);
                        $("#upload_in_progress").dialog('close');
                    }
                });
            });
        });
        // -->
    </script>
    </form>
    </div>

templates/chimere/main_map.html
{% extends "chimere/base.html" %}
{% load i18n unlocalize_point chimere_tags %}
{% block extra_head %}
{% head_jquery %}
{% head_chimere %}
{% head_jme %}
{% head_form %}
<script src="{{ STATIC_URL }}chimere/js/jquery.chimere.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}saclay/js/SaclayCloud.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}saclay/js/jquery.form.js" type="text/javascript"></script>

<script type='text/javascript' language='javascript'>
    <!--
    var default_error_message = "{% trans "Error while loading the page... Refresh the page. If the problem persist contact the webmaster." %}";
    var edit_url = "{% url edit %}";
    var edit_event_url = "{% url edit-event %}";
    var edit_route_url = "{% url edit-route %}";
    // -->
</script>
<script src="{{ STATIC_URL }}saclay/js/interface.js" type="text/javascript"></script>
{{ block.super }}
{% endblock %}
{% block message_edit %}{% endblock %}
{% block sidebar %}
    <div class='sidebar-handler' id='sidebar-handler-hide'>
    </div>
    <div id='action-panel'>
        <ul id='map-actions' class='action'>
            <li id='action-categories' class='state-active'>
                <label>{% trans "Categories" %}</label>
            </li>{% if itinerary_form %}
            <li id='action-routing'>
                <label>{% trans "Routing" %}</label>
            </li>{% endif %}
        </ul>
        <ul id='edit-actions' class='action'>
            <li id='action-edit-marker' class='state-active'>
                <label>{% trans "Location" %}</label>
            </li>
            <li id='action-edit-route'>
                <label>{% trans "Wander" %}</label>
            </li>
            <li id='action-edit-event'>
                <label>{% trans "Event" %}</label>
            </li>
        </ul>
    </div>
    <div id='panel'>
        <div id='map-panel'>
            <form action='.' method='post' name='frm_categories' id='frm_categories'>
                <div id='categories'>{# dynamic content #}
                </div>
            </form>
            {% routing %}
        </div>
        <div id='edit-panel'>
            <div id='frm-edit-marker'>{# dynamic content #}
            </div>
            <div id='frm-edit-route'>{# dynamic content #}
            </div>
            <div id='frm-edit-event'>{# dynamic content #}
            </div>
        </div>
    </div>
    <div class='footer' id='footer-panel'>
        {% if contact_email %}<a href='mailto:{{contact_email}}' id='contactus'>{% trans "contact us" %}</a> | {% endif %}
        <a href='{% url chimere:extra_page '' 'legal' %}' id='page-legal' class='dyn-page'>{% trans "terms of service, credits" %}</a>
    </div>
{% endblock %}
{% block content %}
    <div id='category_description'>
    </div>
    <script type='text/javascript'>
    $(function(){
        $('#category_description').dialog({'autoOpen':false, width:630,
                                           'dialogClass':'no-titlebar'});
    });
    </script>
    <div class='sidebar-handler' id='sidebar-handler-show'>
    </div>
    <div id='detail' class='ui-widget ui-corner-all'></div>
    {% if not itinerary_form %}<div class='map_button'>
        <a href='#' id='button-move-map' class='toggle-button toggle-button-active' onclick='toggleDrawOff();return false;'>
            {% trans "Move on the map" %}
        </a>
        <a href='#' id='button-draw-map' class='toggle-button toggle-button-inactive' onclick='toggleDrawOn();return false;'>
            {% trans "Draw" %}
        </a>
    </div>{% endif %}
    <div id='permalink'></div>
    {% if simple %}
        {% display_welcome 0 %}
    {%else%}
        {% display_welcome news_visible %}
    {% endif %}
    {% display_news news_visible %}
    {{ block.super }}
    <div id='map-shadow'></div>
    <div id='default-message'></div>
<script type="text/javascript">
   <!--
   $("#main-map").show();
   // -->
</script>
    {% map_menu %}
    {% map 'main-map' %}
    <div id='chimere_message'></div>
    <script type='text/javascript'>
    $(function(){$('#chimere_message').dialog({'autoOpen':false,
                      dialogClass:'no-titlebar-simple', position:'right bottom',
                      resizable: false});});
    </script>
{% endblock %}
{% block footer %}
    <p class='map-footer'>{% include "chimere/blocks/footer.html" %}</p>
{% endblock %}

templates/chimere/main_map_simple.html
{% extends "chimere/main_map.html" %}
{% load i18n %}
{% block body_class %}class='simple'{% endblock %}
{% block body_id %}id='simple'{% endblock %}
{% block menu %}{# no menu in simple mode #}{% endblock %}
{% block message_edit %}{% endblock %}
{% block sidebar %}
    <div class='sidebar-handler' id='sidebar-handler-hide'>
    </div>
    <div id='panel'>
        <a>
            <h2>{% trans "Categories"%}</h2>
        </a>
        <form method='post' name='frm_categories' id='frm_categories'>
        <div id='categories' name='categories'></div>
        </form>
    </div>
{% endblock %}
{% block content %}
    <script type='text/javascript'><!--
        var simple = true;
    // --></script>
    {{ block.super }}
{% endblock %}